version: '3.8'

services:
  server_go:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4700:4700"
    environment:
      DB_HOST: postgres_db
      DB_PORT: 5432
      DB_NAME: server_go
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      - postgres_db

  postgres_db:
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      POSTGRES_DB: server_go
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data


  # Enabled when using microservices
  # kafka_server:
  #   build:
  #     context: .
  #     dockerfile: kafka/Dockerfile
  #   ports:
  #     - "9092:9092"

volumes:
  postgres_data:
